# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: pseudobox-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
